;(function(window) {
    'use strict';

    var ClientEventCodes = {
        CODE_CLIENT_NICKNAME_SET: "CODE_CLIENT_NICKNAME_SET",
        CODE_CLIENT_EXIT: "CODE_CLIENT_EXIT",
        CODE_CLIENT_KICK: "CODE_CLIENT_KICK",
        CODE_CLIENT_CONNECT: "CODE_CLIENT_CONNECT",
        CODE_SHOW_OPTIONS: "CODE_SHOW_OPTIONS",
        CODE_SHOW_OPTIONS_SETTING: "CODE_SHOW_OPTIONS_SETTING",
        CODE_SHOW_OPTIONS_PVP: "CODE_SHOW_OPTIONS_PVP",
        CODE_SHOW_OPTIONS_PVE: "CODE_SHOW_OPTIONS_PVE",
        CODE_SHOW_ROOMS: "CODE_SHOW_ROOMS",
        CODE_SHOW_POKERS: "CODE_SHOW_POKERS",
        CODE_ROOM_CREATE_SUCCESS: "CODE_ROOM_CREATE_SUCCESS",
        CODE_ROOM_JOIN_SUCCESS: "CODE_ROOM_JOIN_SUCCESS",
        CODE_ROOM_JOIN_FAIL_BY_FULL: "CODE_ROOM_JOIN_FAIL_BY_FULL",
        CODE_ROOM_JOIN_FAIL_BY_INEXIST: "CODE_ROOM_JOIN_FAIL_BY_INEXIST",
        CODE_ROOM_PLAY_FAIL_BY_INEXIST1: "CODE_ROOM_PLAY_FAIL_BY_INEXIST1",
        CODE_GAME_STARTING: "CODE_GAME_STARTING",
        CODE_GAME_LANDLORD_ELECT: "CODE_GAME_LANDLORD_ELECT",
        CODE_GAME_LANDLORD_CONFIRM: "CODE_GAME_LANDLORD_CONFIRM",
        CODE_GAME_LANDLORD_CYCLE: "CODE_GAME_LANDLORD_CYCLE",
        CODE_GAME_POKER_PLAY: "CODE_GAME_POKER_PLAY",
        CODE_GAME_POKER_PLAY_REDIRECT: "CODE_GAME_POKER_PLAY_REDIRECT",
        CODE_GAME_POKER_PLAY_MISMATCH: "CODE_GAME_POKER_PLAY_MISMATCH",
        CODE_GAME_POKER_PLAY_LESS: "CODE_GAME_POKER_PLAY_LESS",
        CODE_GAME_POKER_PLAY_PASS: "CODE_GAME_POKER_PLAY_PASS",
        CODE_GAME_POKER_PLAY_CANT_PASS: "CODE_GAME_POKER_PLAY_CANT_PASS",
        CODE_GAME_POKER_PLAY_INVALID: "CODE_GAME_POKER_PLAY_INVALID",
        CODE_GAME_POKER_PLAY_ORDER_ERROR: "CODE_GAME_POKER_PLAY_ORDER_ERROR",
        CODE_GAME_OVER: "CODE_GAME_OVER",
        CODE_PVE_DIFFICULTY_NOT_SUPPORT: "CODE_PVE_DIFFICULTY_NOT_SUPPORT",
        CODE_GAME_WATCH: "CODE_GAME_WATCH",
        CODE_GAME_WATCH_SUCCESSFUL: "CODE_GAME_WATCH_SUCCESSFUL"
    };

    var ServerEventCodes = {
        CODE_CLIENT_EXIT: "CODE_CLIENT_EXIT",
        CODE_CLIENT_OFFLINE: "CODE_CLIENT_OFFLINE",
        CODE_CLIENT_NICKNAME_SET: "CODE_CLIENT_NICKNAME_SET",
        CODE_CLIENT_HEAD_BEAT: "CODE_CLIENT_HEAD_BEAT",
        CODE_ROOM_CREATE: "CODE_ROOM_CREATE",
        CODE_ROOM_CREATE_PVE: "CODE_ROOM_CREATE_PVE",
        CODE_GET_ROOMS: "CODE_GET_ROOMS",
        CODE_ROOM_JOIN: "CODE_ROOM_JOIN",
        CODE_GAME_STARTING: "CODE_GAME_STARTING",
        CODE_GAME_LANDLORD_ELECT: "CODE_GAME_LANDLORD_ELECT",
        CODE_GAME_POKER_PLAY: "CODE_GAME_POKER_PLAY",
        CODE_GAME_POKER_PLAY_REDIRECT: "CODE_GAME_POKER_PLAY_REDIRECT",
        CODE_GAME_POKER_PLAY_PASS: "CODE_GAME_POKER_PLAY_PASS",
        CODE_GAME_WATCH: "CODE_GAME_WATCH",
        CODE_GAME_WATCH_EXIT: "CODE_GAME_WATCH_EXIT"
    };

    window.ClientEventCodes = ClientEventCodes;
    window.ServerEventCodes = ServerEventCodes;
} (this));
